// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 * - create an ordered group of docs
 * - render a sidebar for each doc of that group
 * - provide next/previous navigation
 *
 * The sidebars can be generated from the filesystem, or explicitly defined here.
 *
 * Create as many sidebars as you want.
 *
 *
 */
const sectionHeader = (title) => ({
  type: "html",
  value: title,
  className: "navbar__category",
});

const docSidebar = {
  // module.exports = {
  docSidebar: [
    sectionHeader("GETTING STARTED"),
    'intro',
    'benchmarks',

    // GETTING STARTED

    {
      type: 'category',
      label: 'Getting Started',      
      items: [
        'getting-started/quickstart',
        'getting-started/creating-first-pipeline',
        'getting-started/playground',
        // 'getting-started/postgres',
        // 'getting-started/mysql',
        // 'getting-started/mongodb',
        // 'getting-started/oracle',
      ],
    },

    // INSTALL 

    {
      type: 'category',
      label: 'Install',
      items: [
        {
          type: 'category',
          label: 'Docker Compose (UI)',
          link: { type: 'doc', id: 'install/olake-ui/index' },
          items: [
            'install/olake-ui/offline-environments',
          ],
        },
        'install/kubernetes',
        'install/docker-cli',
      ],
    },

    // CONNECTORS
    sectionHeader("CONNECTORS"),
    {
      type: 'category',
      label: 'Sources',
      items: [
        'connectors/postgres/index',
        'connectors/mongodb/index',
        'connectors/mysql/index',
        'connectors/oracle/index',
        'connectors/kafka/index',
      ],
    },


    // Writers
    {
      type: 'category',
      label: 'Destinations',
      items: [
        {
          type: 'category',
          label: 'Apache Iceberg',
          items: [
            {
              type: 'category',
              label: 'Catalogs',
              items: [
                'writers/iceberg/catalog/glue',
                'writers/iceberg/catalog/rest',
                'writers/iceberg/catalog/jdbc',
                'writers/iceberg/catalog/hive',
              ],
            },
            'writers/iceberg/partitioning',
            'writers/iceberg/azure',
            'writers/iceberg/gcp',
            'writers/iceberg/troubleshooting-local',
          ],
        },

        {
          type: 'category',
          label: 'Parquet Writer',
          items: [
            'writers/parquet/config',
            'writers/parquet/permission',
            'writers/parquet/partitioning',
            'writers/parquet/troubleshoot',
            // 'writers/parquet/s3',
            // 'writers/parquet/gcs',
            // 'writers/parquet/local',
            
          ],
        },

      ],
    },

    sectionHeader("UNDERSTANDING OLAKE"),
    {
      type: 'category',
      label: 'Terminologies',
      items: [
        'understanding/terminologies/general',
        'understanding/terminologies/olake',
      ],
    },
    'features/index',
    'core/architecture',
    'understanding/compatibility-catalogs',
    'understanding/compatibility-engines',
    'core/use-cases',

    // Community
    sectionHeader("COMMUNITY"),
    'community/contributing',
    'community/issues-and-prs',
    'community/code-of-conduct',
    'community/channels',

    // Resources category removed as requested
    {
      type: 'link',
      label: 'Roadmap',
      href: 'https://github.com/datazip-inc/olake/?tab=readme-ov-file#-roadmap-highlights',
    },
    // FAQs section removed
    {
      type: 'category',
      label: 'Release Notes',
      items: [
        {
          type: 'autogenerated',
          dirName: 'release', 
        },
      ],
    },
  ],
};

export default docSidebar;